name: Keep Bot Alive
on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Restore data
        run: |
          git pull origin main
          
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - run: pip install telethon cryptg
      - run: timeout 14m python bot.py || true
      
      - name: Save data
        run: |
          git config user.name "actions"
          git config user.email "actions@github.com"
          git add video_index.pkl canales_guardados.json canales_guardados.json usuarios_invitacion.json 2>/dev/null || true
          git diff --staged --quiet || git commit -m "Save data [skip ci]"
          git push
